<?php

return array(
    PARAMETER_IS_EMPTY=>
        array(
            'id'=>PARAMETER_IS_EMPTY,
            'link'=>'',
            'status'=>403,
            'code'=>'PARAMETER_IS_EMPTY',
            'title'=>'数据不能为空',
            'detail'=>'表述传输了一个空数据,但是该数据不能为空.',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    PARAMETER_IS_UNIQUE=>
        array(
            'id'=>PARAMETER_IS_UNIQUE,
            'link'=>'',
            'status'=>409,
            'code'=>'PARAMETER_IS_UNIQUE',
            'title'=>'数据重复',
            'detail'=>'表述传输了一个已经存在的数据,但是该数据不能重复.',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    PARAMETER_FORMAT_ERROR=>
        array(
            'id'=>PARAMETER_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'PARAMETER_FORMAT_ERROR',
            'title'=>'数据格式不正确',
            'detail'=>'表述传输了一个格式不正确的字段.',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    RESOURCE_STATUS_DISABLED=>
        array(
            'id'=>RESOURCE_STATUS_DISABLED,
            'link'=>'',
            'status'=>403,
            'code'=>'RESOURCE_STATUS_DISABLED',
            'title'=>'状态已禁用',
            'detail'=>'表述该资源状态已禁用.',
            'source'=>array(
                'pointer'=>'status'
            ),
            'meta'=>array()
        ),
     RESOURCE_STATUS_ENABLED=>
        array(
            'id'=>RESOURCE_STATUS_ENABLED,
            'link'=>'',
            'status'=>403,
            'code'=>'RESOURCE_STATUS_ENABLED',
            'title'=>'状态已启用',
            'detail'=>'表述该资源状态已启用.',
            'source'=>array(
                'pointer'=>'status'
            ),
            'meta'=>array()
        ),
    RESOURCE_STATUS_ON_SHELF=>
        array(
            'id'=>RESOURCE_STATUS_ON_SHELF,
            'link'=>'',
            'status'=>403,
            'code'=>'RESOURCE_STATUS_ON_SHELF',
            'title'=>'状态已上架',
            'detail'=>'资源状态已上架',
            'source'=>array(
                'pointer'=>'status'
            ),
            'meta'=>array()
        ),
    RESOURCE_STATUS_OFF_STOCK=>
        array(
            'id'=>RESOURCE_STATUS_OFF_STOCK,
            'link'=>'',
            'status'=>403,
            'code'=>'RESOURCE_STATUS_OFF_STOCK',
            'title'=>'状态已下架',
            'detail'=>'资源状态已下架',
            'source'=>array(
                'pointer'=>'status'
            ),
            'meta'=>array()
        ),
    RESOURCE_STATUS_NOT_PENDING=>
        array(
            'id'=>RESOURCE_STATUS_NOT_PENDING,
            'link'=>'',
            'status'=>403,
            'code'=>'RESOURCE_STATUS_NOT_PENDING',
            'title'=>'审核状态非待审核',
            'detail'=>'审核状态非待审核',
            'source'=>array(
                'pointer'=>'applyStatus'
            ),
            'meta'=>array()
        ),
    RESOURCE_STATUS_NOT_REJECT=>
        array(
            'id'=>RESOURCE_STATUS_NOT_REJECT,
            'link'=>'',
            'status'=>403,
            'code'=>'RESOURCE_STATUS_NOT_REJECT',
            'title'=>'审核状态不是已拒绝',
            'detail'=>'资源审核状态不是已拒绝',
            'source'=>array(
                'pointer'=>'applyStatus'
            ),
            'meta'=>array()
        ),
    RESOURCE_STATUS_NOT_ON_SHELF=>
        array(
            'id'=>RESOURCE_STATUS_NOT_ON_SHELF,
            'link'=>'',
            'status'=>403,
            'code'=>'RESOURCE_STATUS_NOT_ON_SHELF',
            'title'=>'状态不是已上架',
            'detail'=>'状态不是已上架',
            'source'=>array(
                'pointer'=>'status'
            ),
            'meta'=>array()
        ),
    RESOURCE_STATUS_NOT_NORMAL=>
        array(
            'id'=>RESOURCE_STATUS_NOT_NORMAL,
            'link'=>'',
            'status'=>403,
            'code'=>'RESOURCE_STATUS_NOT_NORMAL',
            'title'=>'状态非正常状态',
            'detail'=>'状态非正常状态',
            'source'=>array(
                'pointer'=>'status'
            ),
            'meta'=>array()
        ),
    TITLE_FORMAT_ERROR=>
        array(
            'id'=>TITLE_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'TITLE_FORMAT_ERROR',
            'title'=>'标题格式不正确',
            'detail'=>'标题格式错误，长度范围应为1-50位',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    IMAGE_FORMAT_ERROR=>
        array(
            'id'=>IMAGE_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'IMAGE_FORMAT_ERROR',
            'title'=>'图片格式错误',
            'detail'=>'图片格式错误，正确格式为jpg,png,jpeg',
            'source'=>array(
                'pointer'=>'image'
            ),
            'meta'=>array()
        ),
    ATTACHMENT_FORMAT_ERROR=>
        array(
            'id'=>ATTACHMENT_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'ATTACHMENT_FORMAT_ERROR',
            'title'=>'附件格式错误',
            'detail'=>'附件格式错误，正确格式为zip, doc, docx，xls, xlsx，pdf',
            'source'=>array(
                'pointer'=>'attachments'
            ),
            'meta'=>array()
        ),
    REAL_NAME_FORMAT_ERROR=>
        array(
            'id'=>REAL_NAME_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'REAL_NAME_FORMAT_ERROR',
            'title'=>'姓名格式错误',
            'detail'=>'姓名格式错误',
            'source'=>array(
                'pointer'=>'realName'
            ),
            'meta'=>array()
        ),
    CELLPHONE_FORMAT_ERROR=>
        array(
            'id'=>CELLPHONE_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'CELLPHONE_FORMAT_ERROR',
            'title'=>'手机号格式错误',
            'detail'=>'手机号格式错误',
            'source'=>array(
                'pointer'=>'cellphone'
            ),
            'meta'=>array()
        ),
    PRICE_FORMAT_ERROR=>
        array(
            'id'=>PRICE_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'PRICE_FORMAT_ERROR',
            'title'=>'价格格式错误',
            'detail'=>'价格格式错误',
            'source'=>array(
                'pointer'=>'price'
            ),
            'meta'=>array()
        ),
    CARDID_FORMAT_ERROR=>
        array(
            'id'=>CARDID_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'CARDID_FORMAT_ERROR',
            'title'=>'身份证格式不正确',
            'detail'=>'身份证格式不正确',
            'source'=>array(
                'pointer'=>'cardid'
            ),
            'meta'=>array()
        ),
    DATE_FORMAT_ERROR=>
        array(
            'id'=>DATE_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'DATE_FORMAT_ERROR',
            'title'=>'日期格式不正确',
            'detail'=>'日期格式不正确',
            'source'=>array(
                'pointer'=>'date'
            ),
            'meta'=>array()
        ),
    NAME_FORMAT_ERROR=>
        array(
            'id'=>NAME_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'NAME_FORMAT_ERROR',
            'title'=>'名称格式不正确',
            'detail'=>'名称格式不正确',
            'source'=>array(
                'pointer'=>'name'
            ),
            'meta'=>array()
        ),
    NEWS_SOURCE_FORMAT_ERROR=>
        array(
            'id'=>NEWS_SOURCE_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'NEWS_SOURCE_FORMAT_ERROR',
            'title'=>'新闻来源格式不正确',
            'detail'=>'新闻来源格式不正确',
            'source'=>array(
                'pointer'=>'source'
            ),
            'meta'=>array()
        ),
    NEWS_CONTENT_FORMAT_ERROR=>
        array(
            'id'=>NEWS_CONTENT_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'NEWS_CONTENT_FORMAT_ERROR',
            'title'=>'新闻内容格式不正确',
            'detail'=>'新闻内容格式不正确',
            'source'=>array(
                'pointer'=>'content'
            ),
            'meta'=>array()
        ),
    PASSWORD_FORMAT_ERROR=>
        array(
            'id'=>PASSWORD_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'PASSWORD_FORMAT_ERROR',
            'title'=>'密码格式不正确',
            'detail'=>'密码格式不正确',
            'source'=>array(
                'pointer'=>'password'
            ),
            'meta'=>array()
        ),
    PASSWORD_INCORRECT=>
        array(
            'id'=>PASSWORD_INCORRECT,
            'link'=>'',
            'status'=>403,
            'code'=>'PASSWORD_INCORRECT',
            'title'=>'密码不正确',
            'detail'=>'密码不正确',
            'source'=>array(
                'pointer'=>'password'
            ),
            'meta'=>array()
        ),
);
